### ISSUE TITLE
isoType Option doesn't work 

### ISSUE THREAD

**Issue by adriana-olszak** [iambumblehead/json-locale#4]
I'm trying to generate JSONLocales for given config: 

```
JSONLocale.convert({
  outputPath      : "./locale",
  isoType         : "639-1",
  keep            : ["numbers"],
  keepNumberItems : [ "currencyFormatsNumberSystemLatn",
                      "symbolsNumberSystemLatn",
                      "decimalFormatsNumberSystemLatn",
                      "currencies"
                    ],
  localeFilter    : ["de_DE", "de_AT", "fr_FR", "fr_BE", "nl_NL", "nl_BE"]
}, function (err, res) {
  console.log('finished!')
});
```

and I hope that I've correctly understood readme - output of this function should be files with names in ISO-639-1 which have format e.g `'en_GB'` in folder named `locale`.

But output is different. Files are generated in ISO-639-2 in output folder - `JSONlocaleNew`

Did I specified something wrong?

**Comment by iambumblehead** [comment]
@Errindel I'll investigate and respond, thanks for visiting and opening and issue

**Comment by iambumblehead** [comment]
@Errindel I updated json-locale and confirm the behaviour using this
```javascript
const jsonlocale = require('json-locale');

jsonlocale.convert({
  outputDir : "./locale",
  isoType : "639-1",
  keep : ["numbers"],
  keepNumberItems : [
    "currencyFormatsNumberSystemLatn",
    "symbolsNumberSystemLatn",
    "decimalFormatsNumberSystemLatn",
    "currencies"
  ],
  localeFilter : [
    "de_DE", "de_AT", "fr_FR", "fr_BE", "nl_NL", "nl_BE"
  ]
}, (err, res) => {
  console.log('finished!');
});
```
I updated the readme. This repo is somewhat 'old' for me and does not include unit tests. Please feel free to report any issue you may have.

```bash
[...] write: ./locale/nl_NL.json
[...] write: ./locale/nl_BE.json
[...] write: ./locale/fr_FR.json
[...] write: ./locale/fr_BE.json
[...] write: ./locale/de_DE.json
[...] write: ./locale/de_AT.json
```

Would you confirm that the new version 0.0.49 (published to npm) is working for you using the property name "outputDir"? If you will confirm the issue is resolved this issue may be closed.

**Comment by adriana-olszak** [comment]
@iambumblehead thanks for so quick response! Everything works fine now : )) And thanks for developing such package it will be very useful for us
