### ISSUE TITLE
Why locale is separeted by _ instead of - ??

### ISSUE THREAD

**Issue by adriana-olszak** [iambumblehead/json-locale#5]
I'm planning to use your pckg to implemented localiztion functions in our product. I've started to read about locale format and I can see that `rfc5646` defined hyphen as a separator.  https://tools.ietf.org/html/rfc5646

In our product we use locale in format 'de-DE' as it's following `rfc5646`

So here are my questions: 
Is there some reason for using `_` as a separator?? 
Is there any possibility to switch from `_` to '-'??

**Comment by iambumblehead** [comment]
Sure I'll change it and update the major version number in case anyone else might be using it. One moment...

**Comment by iambumblehead** [comment]
```
[...] write: ./locale/nl-NL.json
[...] write: ./locale/nl-BE.json
[...] write: ./locale/fr-FR.json
[...] write: ./locale/fr-BE.json
[...] write: ./locale/de-DE.json
[...] write: ./locale/de-AT.json
```
I published it as version 0.1.0

**Comment by iambumblehead** [comment]
@Errindel I updated json-locale and added [tests](https://travis-ci.org/iambumblehead/json-locale)

please use the newest version :)

**Comment by iambumblehead** [comment]
I'm closing this...
